// Generated by IcedCoffeeScript 1.3.3e

define(['jquery'], function($) {
  return $('button').bind('click', function(e) {
    e.preventDefault();
    e.stopImmediatePropagation();
    return console.log('clicked button');
  });
});
