// Generated by IcedCoffeeScript 1.3.3e

define(['jquery', 'sockrpc', 'synapse', 'synapse/object'], function($, RPC, Synapse, ObjectAdapter) {
  var Remote, future;
  Remote = RPC('index', 'industry');
  future = Remote.industry();
  return future(function() {
    return console.log(arguments);
  });
});
